name: Deploy demo-frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
  uses: actions/checkout@v4

- name: Login to docker hub
  run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

- name: Build Docker Image
  run: docker build -t jayadhav/demo-frontend .

- name: Publish Image to docker hub
  run: docker push jayadhav/demo-frontend:latest


  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull jayadhav/demo-frontend:latest
      - name: Delete old container
        run: docker rm -f demo-frontend-container
      - name: Run Docker Container
        run: docker run -d -p 5173:80 --name demo-frontend-container -e MONGO_PASSWORD='${{ secrets.MONGO_PASSWORD }}' jayadhav/demo-frontend
